### ISSUE TITLE
blockchain_height and miner_height 

### ISSUE THREAD

**Issue by herci85** [pperzyna/bobcat_exporter#2]
I'm no expert but it looks like the blockchain_height and the miner_height are getting the same value during syncing.
I think the problem is in main.go  line 197
`ch <- prometheus.MustNewConstMetric(e.bobcatStatusBlockchainHeight.Desc(), prometheus.GaugeValue, parseString(status.MinerHeight))`
 
Otherwise great work. Thanks

**Comment by pperzyna** [comment]
Resolved by #3
